project:
  type: website

execute:
    freeze: auto

website:
  title: "R Club Würzburg"
  navbar:
    background: secondary
    search: true
    right:
      - href: index.qmd
        text: Home
      - slides.qmd
      - about.qmd
  repo-url: https://github.com/Hillea/rclubwue
  repo-actions: [edit, issue]

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual



