---
title: "R Club Würzburg"
---

This is the course website of the R Club of the [Research Training Group 2660](https://www.uni-wuerzburg.de/grk2660/news/) at the University and University Clinic in Würzburg, Germany - but it's open to everyone if space is available!

The R Club is a hands-on beginner-friendly R course/coding club. We will start with the basics and will switch to topics that are of interest to the majority (similar to a Journal Club). In the beginning, Lea will teach, but the format may change to others presenting solutions to problems they encountered or topics they find interesting. We may end up as a Data Dojo/Coding Club, where we work on problems together. This way, we can all learn together!

We meet weekly on Tuesdays, 16:00 - 18:00 in Room 213 at the Marcusstr, starting in January 2024. The syllabus can be found [here](https://docs.google.com/document/d/1ZJPsgPMPv_2EYwyGL7kv9Mb846iilznj3cuKNvwuINc/edit#heading=h.9xs7fuefba6l). On this page, the slides etc. will be linked.

+-----------+--------------+-----------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| # Session | # Date       | # Topic                                 | # Preparation/Notes                                                                                                                                                                                                                                                                                                                                                                                 |
|           |              |                                         |                                                                                                                                                                                                                                                                                                                                                                                                     |
| 1         | 16.01.24     | Intro to R & RStudio                    | [Install R and RStudio](https://rstudio-education.github.io/hopr/starting.html), download [Dataset1](https://github.com/Hillea/rclubwue/blob/main/Slides/Data/ahi-cesd.csv), [Dataset2](https://github.com/Hillea/rclubwue/blob/main/Slides/Data/participant-info.csv)                                                                                                                              |
+-----------+--------------+-----------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2         | 23.01.24     | Data Wrangling                          | Download Datasets [1](https://github.com/Hillea/rclubwue/blob/main/Slides/Data/responses.csv), [2](https://github.com/Hillea/rclubwue/blob/main/Slides/Data/qformats.csv), [3](https://github.com/Hillea/rclubwue/blob/main/Slides/Data/scoring.csv), & [4](https://github.com/Hillea/rclubwue/blob/main/Slides/Data/pinfo.csv) (click on link and symbol for "download raw file" on the top-right) |
+-----------+--------------+-----------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|           | 30.01.24     | No R Club! (Clinical Research Workshop) | Self-study instead: Please have a look at the [rest of the data wrangling presentation](https://hillea.github.io/rclubwue/Slides/W2b_DataWranglingR.html#/data-wrangling-3) and/or [chapter 6 of Fundamentals of Quantitative Analysis](https://psyteachr.github.io/quant-fun-v2/data-wrangling-3.html)!                                                                                            |
+-----------+--------------+-----------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 3         | 06.02.24     | Randomization & Counterbalancing        | (Ecem)                                                                                                                                                                                                                                                                                                                                                                                              |
+-----------+--------------+-----------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 4         | **14**.02.24 | Data Wrangling 2 & first Visualization  | (Uni closed in the afternoon - carnival? **Meet on Wednesday, 14th, 15:00 in 213**)                                                                                                                                                                                                                                                                                                                 |
|           |              |                                         |                                                                                                                                                                                                                                                                                                                                                                                                     |
|           |              |                                         | Download Datasets: [participant-info.csv](https://psyteachr.github.io/quant-fun-v2/participant-info.csv) & [ahi-cesd.csv](https://psyteachr.github.io/quant-fun-v2/ahi-cesd.csv) / [Speed Dating Data](https://github.com/Hillea/rclubwue/blob/main/Slides/Data/Speed%20Dating%20Data.csv) & [Codebook](https://github.com/Hillea/rclubwue/blob/main/Slides/Data/Speed%20Dating%20Data%20Key.doc)\  |
|           |              |                                         |                                                                                                                                                                                                                                                                                                                                                                                                     |
|           |              |                                         | Use the [exercise.Rmd](https://github.com/Hillea/rclubwue/blob/main/Slides/W4_exercises.Rmd) and the speed dating data!                                                                                                                                                                                                                                                                             |
+-----------+--------------+-----------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|           | 20.02.24     | No R Club!                              |                                                                                                                                                                                                                                                                                                                                                                                                     |
+-----------+--------------+-----------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 5         | 27.02.24     | Preprocessing, e.g. physio data?        | (Francesco)                                                                                                                                                                                                                                                                                                                                                                                         |
+-----------+--------------+-----------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 6         | 5.03.24      | Data Viz                                | Data: [participant-info.csv](https://psyteachr.github.io/quant-fun-v2/participant-info.csv) & [ahi-cesd.csv](https://psyteachr.github.io/quant-fun-v2/ahi-cesd.csv)                                                                                                                                                                                                                                 |
+-----------+--------------+-----------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|           | 12.03.24     | No R Club!                              |                                                                                                                                                                                                                                                                                                                                                                                                     |
+-----------+--------------+-----------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 7         | **21**.03.24 | Data Viz 2                              | We'll meet on **Thursday, 21st of March**, at **15:00**. You may join via [Zoom](https://uni-wuerzburg.zoom-x.de/j/67346239699?pwd=TTlBZkVRRWliRHFPME11eTlkVEZNZz09) (but it might be more difficult to follow).\                                                                                                                                                                                   |
|           |              |                                         | \                                                                                                                                                                                                                                                                                                                                                                                                   |
|           |              |                                         | We will make a nice plot with Ulkar's real data!                                                                                                                                                                                                                                                                                                                                                    |
+-----------+--------------+-----------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 8         | 16.04.24     | Stats 1                                 | Quick intro with a focus on ANOVA, or start with t-tests and do it in-depths across several weeks?                                                                                                                                                                                                                                                                                                  |
+-----------+--------------+-----------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 9         | 30.04.24     | Hands-on ANOVA                          | Running ANOVAs in R (with your own data?)                                                                                                                                                                                                                                                                                                                                                           |
+-----------+--------------+-----------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 10        |              | Writing Reports                         |                                                                                                                                                                                                                                                                                                                                                                                                     |
+-----------+--------------+-----------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 11        |              | R Projects, Git                         |                                                                                                                                                                                                                                                                                                                                                                                                     |
+-----------+--------------+-----------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 12        |              | Functions?                              |                                                                                                                                                                                                                                                                                                                                                                                                     |
+-----------+--------------+-----------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

```{r}
print("Hello World")
```
